//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilizeYou.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobilizeYou.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string FormCustomers_deleteToolStripMenuItem_Click_Are_you_sure_ {
            get {
                return ResourceManager.GetString("FormCustomers_deleteToolStripMenuItem_Click_Are_you_sure_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Licence.
        /// </summary>
        internal static string FormCustomers_FillData_Drive_Licence {
            get {
                return ResourceManager.GetString("FormCustomers_FillData_Drive_Licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FormCustomers_FillData_Full_Name {
            get {
                return ResourceManager.GetString("FormCustomers_FillData_Full_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string FormCustomers_FillData_Id {
            get {
                return ResourceManager.GetString("FormCustomers_FillData_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Card.
        /// </summary>
        internal static string FormCustomers_FillData_Identity_Card {
            get {
                return ResourceManager.GetString("FormCustomers_FillData_Identity_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string FormCustomers_FillData_Phone_Number {
            get {
                return ResourceManager.GetString("FormCustomers_FillData_Phone_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string FormEmployee_Refresh__0 {
            get {
                return ResourceManager.GetString("FormEmployee_Refresh__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string FormLogin_buttonLogin_Click_Error {
            get {
                return ResourceManager.GetString("FormLogin_buttonLogin_Click_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name or Password is invalid..
        /// </summary>
        internal static string FormLogin_buttonLogin_Click_User_name_or_Password_is_invalid_ {
            get {
                return ResourceManager.GetString("FormLogin_buttonLogin_Click_User_name_or_Password_is_invalid_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string FormProduct_deleteToolStripMenuItem_Click_Are_you_sure_ {
            get {
                return ResourceManager.GetString("FormProduct_deleteToolStripMenuItem_Click_Are_you_sure_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Fail..
        /// </summary>
        internal static string FormProduct_deleteToolStripMenuItem_Click_Delete_Fail_ {
            get {
                return ResourceManager.GetString("FormProduct_deleteToolStripMenuItem_Click_Delete_Fail_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Successfully..
        /// </summary>
        internal static string FormProduct_deleteToolStripMenuItem_Click_Delete_Successfully_ {
            get {
                return ResourceManager.GetString("FormProduct_deleteToolStripMenuItem_Click_Delete_Successfully_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string FormProduct_deleteToolStripMenuItem_Click_Warning {
            get {
                return ResourceManager.GetString("FormProduct_deleteToolStripMenuItem_Click_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0.
        /// </summary>
        internal static string FormProduct_Refresh__0_0 {
            get {
                return ResourceManager.GetString("FormProduct_Refresh__0_0", resourceCulture);
            }
        }
    }
}
